
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/justplay
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ##ADD URI HERE

###############################################
########### JUSTPLAY PROPERTIES ###############
###############################################

