server:
  servlet:
    context-path: /justplay

spring:
  application:
    name: JustPlay
  profiles:
    active: prod
  #jackson:
    #default-property-inclusion: NON_NULL
    #serialization:
      #write-dates-as-timestamps: true
  messages:
    basename: i18n/common, i18n/justplay
    encoding: UTF-8
    use-code-as-default-message: true
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
        hbm2ddl.auto: update
        #format_sql: true
        #show_sql: true
    open-in-view: false

###############################################
############# JUSTPLAY PROPERTIES #############
###############################################

justplay:
  dateformat: dd/MM/yyyy