
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/justplay?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  

###############################################
########### JUSTPLAY PROPERTIES ###############
###############################################

